# Generated by Django 3.0.6 on 2020-06-02 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=400, verbose_name='Название')),
                ('cloud_link', models.URLField(verbose_name='Ссылка на облако')),
                ('public_link', models.URLField(verbose_name='Публичная ссылка')),
                ('loaded_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_favourite', models.BooleanField(default=True, verbose_name='В избранных')),
                ('loaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Кем загружена')),
            ],
        ),
    ]
